version: '3'
services:
  webserver:
    build: webserver/
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /home/pollbuddy/dev-site-configs:/etc/nginx/conf.d/dev-site-configs
      - /home/pollbuddy/meetings:/var/www-meetings
    links:
      - php

  php:
    image: php:7-fpm
