# Allocate volumes for data storage
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: poll-buddy-management-server-volume-claim-instances
  labels:
    app.kubernetes.io/name: poll-buddy-management-server
    app.kubernetes.io/component: management-server
    app.kubernetes.io/part-of: poll-buddy
    app: poll-buddy-management-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: poll-buddy-management-server-volume-claim-configurations
  labels:
    app.kubernetes.io/name: poll-buddy-management-server
    app.kubernetes.io/component: management-server
    app.kubernetes.io/part-of: poll-buddy
    app: poll-buddy-management-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# Create a service to access the deployment pods
---
apiVersion: v1
kind: Service
metadata:
  name: poll-buddy-management-server-service
  labels:
    app.kubernetes.io/name: poll-buddy-management-server
    app.kubernetes.io/component: management-server
    app.kubernetes.io/part-of: poll-buddy
    app: poll-buddy-management-server
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: poll-buddy-management-server
    app.kubernetes.io/component: management-server
    app.kubernetes.io/part-of: poll-buddy
    app: poll-buddy-management-server
  type: NodePort

# Service Accounts and Authorizations
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: poll-buddy-management-server-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: poll-buddy-management-server-service-role
rules:
  - apiGroups: ["*"]
    resources: ["configmaps"]
    verbs: ["*"]
  - apiGroups: ["*"]
    resources: ["deployments"]
    verbs: ["*"]
  - apiGroups: ["*"]
    resources: ["deployments/scale"]
    verbs: ["*"]
  - apiGroups: ["*"]
    resources: ["services"]
    verbs: ["*"]
  - apiGroups: ["*"]
    resources: ["pods"]
    verbs: ["*"]
  - apiGroups: ["*"]
    resources: ["secrets"]
    verbs: ["*"]
  - apiGroups: ["*"]
    resources: ["serviceaccounts"]
    verbs: ["*"]
  - apiGroups: ["*"]
    resources: ["clusterrolebindings"]
    verbs: ["*"]
  - apiGroups: ["*"]
    resources: ["clusterroles"]
    verbs: ["*"]
  - apiGroups: ["*"]
    resources: ["persistentvolumeclaims"]
    verbs: ["*"]
  - apiGroups: ["*"]
    resources: ["statefulsets"]
    verbs: ["*"]
  - apiGroups: ["*"]
    resources: ["statefulsets/scale"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: poll-buddy-management-server-service-role-binding
subjects:
  - kind: ServiceAccount
    name: poll-buddy-management-server-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: poll-buddy-management-server-service-role
  apiGroup: rbac.authorization.k8s.io

# Create a priority class to make sure the management pods don't get evicted or can't be scheduled
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: poll-buddy-high-priority
value: 1000
preemptionPolicy: PreemptLowerPriority
globalDefault: false
description: "This priority class should be used for managing service pods only."


# Create a priority class to make sure the main instance don't get evicted or can't be scheduled
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: poll-buddy-medium-priority
value: 100
preemptionPolicy: PreemptLowerPriority
globalDefault: false
description: "This priority class should be used for the main production pods only."


# Create a priority class for the dev instances which can get evicted or failed to schedule
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: poll-buddy-low-priority
value: 1
preemptionPolicy: Never
globalDefault: true
description: "This priority class should be used for the development test instances and other low priority pods."

# Create a deployment to run in
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll-buddy-management-server
  labels:
    app.kubernetes.io/name: poll-buddy-management-server
    app.kubernetes.io/component: management-server
    app.kubernetes.io/part-of: poll-buddy
    app: poll-buddy-management-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: poll-buddy-management-server
      app.kubernetes.io/component: management-server
      app.kubernetes.io/part-of: poll-buddy
      app: poll-buddy-management-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: poll-buddy-management-server
        app.kubernetes.io/component: management-server
        app.kubernetes.io/part-of: poll-buddy
        app: poll-buddy-management-server
    spec:
      serviceAccountName: poll-buddy-management-server-service-account
      shareProcessNamespace: true
      restartPolicy: Always
      priorityClassName: poll-buddy-high-priority
      containers:
        - name: proxy-server
          image: pollbuddy/proxy-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: dev-site-configs
              mountPath: /usr/local/apache2/conf/dynamic
          # Probes to report the status of the application
          startupProbe: # Runs to know when the app started up
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            failureThreshold: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
            initialDelaySeconds: 5
          readinessProbe: # Runs to make sure the app is ready to receive requests
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            failureThreshold: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            initialDelaySeconds: 5
          livenessProbe: # Runs to make sure the app is alive
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            failureThreshold: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            initialDelaySeconds: 5

        - name: dev-controller
          image: pollbuddy/dev-controller:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: dev-site-instances
              mountPath: /app/instances
            - name: dev-site-configs
              mountPath: /app/configurations
          env:
            - name: CLUSTER_DNS_SUBDOMAIN
              value: default.svc.cluster.local
            - name: EXPRESS_SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: poll-buddy-management-server-secrets
                  key: session_secret
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: poll-buddy-management-server-secrets
                  key: github_client_id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: poll-buddy-management-server-secrets
                  key: github_client_secret
            - name: CICD_KEY
              valueFrom:
                secretKeyRef:
                  name: poll-buddy-management-server-secrets
                  key: github_cicd_key
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          # Probes to report the status of the application
          startupProbe: # Runs to know when the app started up
            httpGet:
              path: /api
              port: 3000
              scheme: HTTP
            failureThreshold: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
            initialDelaySeconds: 5
          readinessProbe: # Runs to make sure the app is ready to receive requests
            httpGet:
              path: /api
              port: 3000
              scheme: HTTP
            failureThreshold: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            initialDelaySeconds: 5
          livenessProbe: # Runs to make sure the app is alive
            httpGet:
              path: /api
              port: 3000
              scheme: HTTP
            failureThreshold: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            initialDelaySeconds: 5
      volumes:
        - name: dev-site-instances
          persistentVolumeClaim:
            claimName: poll-buddy-management-server-volume-claim-instances
        - name: dev-site-configs
          persistentVolumeClaim:
            claimName: poll-buddy-management-server-volume-claim-configurations
