# Secrets
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: poll-buddy-management-server-secrets
  labels:
    app.kubernetes.io/name: poll-buddy-management-server
    app.kubernetes.io/component: management-server
    app.kubernetes.io/part-of: poll-buddy
    app: poll-buddy-management-server
data:
  # This should be changed
  session_secret: CHANGEME
  github_client_id: CHANGEME
  github_client_secret: CHANGEME
  github_cicd_key: CHANGEME
