name: CI-Docker-Build
on:
  push:

jobs:
  Docker-Build-Proxy-Server:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: pollbuddy/proxy-server
          tags: |
            type=ref,event=branch
            type=sha,format=long,prefix=,suffix=
            type=sha,format=long,suffix=-{{branch}}
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:webserver/"
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

  Docker-Build-Dev-Server:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: pollbuddy/dev-controller
          tags: |
            type=ref,event=branch
            type=sha,format=long,prefix=,suffix=
            type=sha,format=long,suffix=-{{branch}}
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:dev-controller/"
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
